#!/bin/sh
#
# .git/hooks/pre-commit
#
# Don't allow a commit with failing tests or inconsistent formatting.
#

# Exit immediately with nonzero status if any untested command fails.
set -e

# Stash any unstaged changes, including untracked files, leaving only changes
# which are staged for commit.
#
# NOTE: Ignored files are not touched.
#
git stash push --include-untracked --keep-index --quiet

# If there are any python files staged for commit, check their formatting.
set -- $(git diff --staged --name-only -- \*.py)
if test $# -gt 0 && ! black --quiet --check "$@"; then
    black .
    cat <<\EOF

Please review the formatted files and stage the new changes before committing.

EOF
    exit 1
fi

# Make sure the tests pass with the staged changes.
python -m pytest --quiet

# Restore the dirty state of the worktree, and commit.
git stash pop --quiet
