#!/bin/sh
#
# .git/hooks/pre-commit
#
# Don't allow a commit if:
#     - There are unstaged changes
#     - There are untracked files
#     - There are files with inconsistent formatting
#     - There are failing tests
#
set --

while IFS= read -r line
do
    case "$line" in
    [MA]' '*)  # Adding or modifying files.
        # Populate argv with staged python files.
        if test -n "${line%%*.py}"
        then
            continue
        fi
        pyfile="${line#[MA]'  '}"
        set -- "$@" "$pyfile"
        ;;
    '')
        # Not committing anything, e.g. `--amend`.
        exit 0
        ;;
    *)
        cat <<\EOF
Cannot run pre-commit checks with a dirty worktree.

Clean up unstaged and untracked files by running:

    git stash --include-untracked --keep-index

Then try committing again.

EOF
        exit 1
        ;;
    esac
done <<EOF
$(git status --porcelain --untracked=all)
EOF

if test $# -gt 0 && ! black --quiet --check "$@"
then
    black "$@"
    cat <<\EOF

Please review the formatted files and stage the new changes before committing.

EOF
    exit 1
fi

if ! python -m pytest --quiet
then
    exit 1
fi

exit 0
